### PR TITLE
Re-enable support for Node 16.9+

### PR DESCRIPTION
**Pull request by nathanchapman**

### CODE REVIEW

**Review by wokkaflokka — APPROVED** [review]
🥇

**Review by tizmagik — APPROVED** [review]

**Comment by tizmagik** [comment]
Thanks!

**Comment by tizmagik** [comment]
Released as [v9.3.1](https://github.com/nytimes/react-tracking/releases/tag/v9.3.1)

**Comment by nathanchapman** [comment]
Thank you @tizmagik!

**Pull request merged**
