### PR TITLE
Add additional peer dependency to allow use with react 18

### PR DESCRIPTION
**Pull request by AnthonyCrowcroft**
Hey really keen to keep using this library but we are shifting up to react 18 so am needing to get this added in, all the tests are still passing as expected and the devDependency remains unchanged as no newer functionality is required therefore no older peer dependencies are required to be removed.

TLDR; very minor change that lets more people use the library :)

### CODE REVIEW

**Comment by AnthonyCrowcroft** [comment]
@tizmagik you mentioned this being something you were happy to look at a PR for but I am new to contributing to this project any additional things I need to do to get this merged in for me to use.  🚀

**Comment by tizmagik** [comment]
Oh I'm sorry I missed this earlier. Let me merge and cut a new release later today!

**Review by tizmagik — APPROVED** [review]

**Comment by AnthonyCrowcroft** [comment]
@tizmagik if at all possible please post a comment here so I can pull the new version into my project.

**Comment by tizmagik** [comment]
Published as [v9.2.1](https://github.com/nytimes/react-tracking/releases/tag/v9.2.1) -- thanks again @AnthonyCrowcroft !

**Pull request merged**
