### PR TITLE
Switch to Github Actions

### PR DESCRIPTION
**Pull request by tizmagik**
Looks like open source Drone is no longer a thing...?

... and NYT doesn't allow GHA ... hmm

### CODE REVIEW

**Comment by bgergen** [comment]
Hmmm weird, I don't remember hearing anything about a change here. I can check in with folks to see what the recommended course of action is.

**Comment by bgergen** [comment]
@tizmagik Following up on this. Apparently there are [major issues](https://community.harness.io/t/drone-cloud-builds-stuck-in-pending/12809) with Cloud Drone and DV is looking into alternatives (including GHA). I added myself as a watcher to their Jira ticket and there seem to be a number of other folks pressing them on this as well. I'll update here as soon as I hear more.

**Comment by bgergen** [comment]
@tizmagik GitHub Actions are now supposedly enabled on this repo. Not sure how to test it though—maybe try pushing an empty commit to force the build to try to run again?

**Comment by bgergen** [comment]
@tizmagik Did it work? I'm not quite sure what I'm supposed to be seeing.

**Comment by tizmagik** [comment]
Hmm, doesn't look like it's triggering? Will try and take a closer look at this when I get a chance.

**Comment by tizmagik** [comment]
GHA still don't seem to be triggering? Maybe we could try merging this PR and then open a new one against that? I wonder if the workflow needs to be in main for it to trigger? 🤷

**Comment by bgergen** [comment]
> GHA still don't seem to be triggering? Maybe we could try merging this PR and then open a new one against that? I wonder if the workflow needs to be in main for it to trigger? 🤷

Ohhhh that could certainly be the case. I say go for it and let's see what happens—if it still doesn't work I can bug DV to take a look at at the repo and let us know what we're missing.

**Comment by tizmagik** [comment]
@bgergen ha! chatgpt found the bug 😂  https://github.com/nytimes/react-tracking/pull/214/commits/faa372fa4dae6c30dc75c7850b595c3fa868c795

**Comment by bgergen** [comment]
omg

**Review by bgergen — APPROVED** [review]

**Pull request merged**
