### PR TITLE
upgrade babel dependencies + config to support core-js@3

### LINKED ISSUE #119: Module not found: Error: Can't resolve 'core-js/modules/es6.function.bind
I'm getting this error after upgrade to v5.7.0

Captura de pantalla de 2019-03-21 15-58-26

It is the only package that give me that error :thinking: 
Maybe it is because I'm using core-js v3? :thinking: 
```
"react-tracking": "^5.7.0"
"@babel/core": "^7.4.0"
"@babel/runtime-corejs3": "^7.4.2"
"core-js": "^3.0.0"
"regenerator-runtime": "^0.13.2"
"@babel/runtime": "^7.2.0"
"@babel/plugin-transform-runtime": "^7.4.0"
```

### PR DESCRIPTION
**Pull request by mckernanin**
(likely a breaking change for core-js@2)

Fixes #119

### CODE REVIEW

**Comment by mckernanin** [comment]
Build is failing because core-js isn't installed/updated. Not sure if there's something special that needs to happen to update the peer dependency, I'm not super familiar with them.

**Comment by mckernanin** [comment]
Yep, adding it to the dependencies fixed the build. In master, core-js is in the lock file but not package.json. Is there a "right way" to do that, or just manually remove it from package.json?

**Comment by tizmagik** [comment]
I think having it as a `peerDep` is preferred in this case and then having it as a `devDep` would fix the build

**Comment by mckernanin** [comment]
Ah ok. Bumping the branch shortly.

**Comment by tizmagik** [comment]
Thanks @mckernanin I think I'll lump this with #124 so that we don't have 2 breaking releases back to back.

**Comment by mckernanin** [comment]
Sounds good, thanks!

**Comment by tizmagik** [comment]
Released as [v7.0.0](https://github.com/nytimes/react-tracking/releases/tag/v7.0.0) 🎉 Please holler (or open a new issue) if you see any problems.

**Pull request merged**
